# Generated by Django 4.2.30 on 2026-04-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_complaint_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="location",
            field=models.CharField(
                choices=[
                    (
                        "Boys Hostels",
                        (
                            ("Block 1 (Boys)", "Block 1"),
                            ("Block 2 (Boys)", "Block 2"),
                            ("Block 3 (Boys)", "Block 3"),
                            ("Block 4 (Boys)", "Block 4"),
                            ("Block 5 (Boys)", "Block 5"),
                            ("Block 6 (Boys)", "Block 6"),
                            ("Block 7 (Boys)", "Block 7"),
                            ("Block 8 (Boys)", "Block 8"),
                            ("Block 9 (Boys)", "Block 9"),
                            ("Block 10 (Boys)", "Block 10"),
                            ("Block 14 (Boys)", "Block 14"),
                            ("Block 15 (Boys)", "Block 15"),
                            ("Block 16 (Boys)", "Block 16"),
                            ("Block 17 (Boys)", "Block 17"),
                            ("Block 18 (Boys)", "Block 18"),
                            ("Block 19 (Boys)", "Block 19"),
                            ("Block 20 (Boys)", "Block 20"),
                        ),
                    ),
                    (
                        "Girls Hostels",
                        (
                            ("Block 11 (Girls)", "Block 11"),
                            ("Block 12 (Girls)", "Block 12"),
                            ("Block 13 (Girls)", "Block 13"),
                            ("Block 21 (Girls)", "Block 21"),
                            ("Block 22 (Girls)", "Block 22"),
                        ),
                    ),
                    (
                        "Other Locations",
                        (
                            ("Library", "Library"),
                            ("Lab 1", "Lab 1"),
                            ("Main Gate", "Main Gate"),
                            ("Cafeteria", "Cafeteria"),
                            ("Other", "Other"),
                        ),
                    ),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
