# Generated by Django 4.2.30 on 2026-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_complaint_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="gender",
            field=models.CharField(
                choices=[("Boys", "Boys"), ("Girls", "Girls"), ("Other", "Other")],
                default="Other",
                max_length=10,
            ),
        ),
    ]
